version: "3.9"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust


  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    command: ['./wait-for-it.sh', 'postgres:5432', '--',
              'python', 'manage.py', 'runserver', '0.0.0.0:8000']
